name: Theos CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v3
 
    - name: Run Theos action
      uses: itsnebulalol/theos-action@main
      with:
        theos-src: "https://github.com/L1ghtmann/theos"
        theos-branch: "rootless-rpaths"
        theos-sdks: "https://github.com/chrisharper22/sdks"
        theos-sdks-branch: "main"
      
    - name: Build tweak
      run: gmake clean package FINALPACKAGE=1 -j$(sysctl -n hw.physicalcpu)
          
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: pkg.deb
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.workspace }}/packages/*.deb
